// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/structs.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MixConfig struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
}

func (m *MixConfig) Reset()         { *m = MixConfig{} }
func (m *MixConfig) String() string { return proto.CompactTextString(m) }
func (*MixConfig) ProtoMessage()    {}
func (*MixConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{0}
}

func (m *MixConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MixConfig.Unmarshal(m, b)
}
func (m *MixConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MixConfig.Marshal(b, m, deterministic)
}
func (m *MixConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MixConfig.Merge(m, src)
}
func (m *MixConfig) XXX_Size() int {
	return xxx_messageInfo_MixConfig.Size(m)
}
func (m *MixConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MixConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MixConfig proto.InternalMessageInfo

func (m *MixConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MixConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *MixConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MixConfig) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type ClientConfig struct {
	Id                   string     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Host                 string     `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 string     `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
	PubKey               []byte     `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Provider             *MixConfig `protobuf:"bytes,5,opt,name=Provider,proto3" json:"Provider,omitempty"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{1}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ClientConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *ClientConfig) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *ClientConfig) GetProvider() *MixConfig {
	if m != nil {
		return m.Provider
	}
	return nil
}

type GeneralPacket struct {
	Flag                 []byte   `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *GeneralPacket) Reset()         { *m = GeneralPacket{} }
func (m *GeneralPacket) String() string { return proto.CompactTextString(m) }
func (*GeneralPacket) ProtoMessage()    {}
func (*GeneralPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{2}
}

func (m *GeneralPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralPacket.Unmarshal(m, b)
}
func (m *GeneralPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralPacket.Marshal(b, m, deterministic)
}
func (m *GeneralPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralPacket.Merge(m, src)
}
func (m *GeneralPacket) XXX_Size() int {
	return xxx_messageInfo_GeneralPacket.Size(m)
}
func (m *GeneralPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralPacket proto.InternalMessageInfo

func (m *GeneralPacket) GetFlag() []byte {
	if m != nil {
		return m.Flag
	}
	return nil
}

func (m *GeneralPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PullRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{3}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *PullRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*MixConfig)(nil), "config.MixConfig")
	proto.RegisterType((*ClientConfig)(nil), "config.ClientConfig")
	proto.RegisterType((*GeneralPacket)(nil), "config.GeneralPacket")
	proto.RegisterType((*PullRequest)(nil), "config.PullRequest")
}

func init() { proto.RegisterFile("config/structs.proto", fileDescriptor_f9a12e0597d01ddf) }

var fileDescriptor_f9a12e0597d01ddf = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xdd, 0x2d, 0xbb, 0xb3, 0x55, 0x30, 0x2c, 0x12, 0x3c, 0x95, 0x9e, 0x7a, 0xb1,
	0x82, 0x1e, 0x3c, 0x7a, 0x58, 0x51, 0x17, 0x11, 0x42, 0xf0, 0xe6, 0x29, 0xdb, 0x8e, 0x4b, 0xd9,
	0xd0, 0x68, 0x9a, 0x8a, 0x3e, 0x84, 0xef, 0x2c, 0x9d, 0x94, 0xbc, 0xc1, 0xde, 0xfe, 0xff, 0x23,
	0x61, 0xe6, 0x1b, 0x58, 0xd7, 0xb6, 0xfb, 0x68, 0xf7, 0xd7, 0xbd, 0x77, 0x43, 0xed, 0xfb, 0xea,
	0xd3, 0x59, 0x6f, 0x79, 0x1a, 0x68, 0xf1, 0x0e, 0xcb, 0xd7, 0xf6, 0x67, 0x43, 0x85, 0x9f, 0x41,
	0xb2, 0x6d, 0x04, 0xcb, 0x59, 0xb9, 0x54, 0xc9, 0xb6, 0xe1, 0x1c, 0x66, 0xcf, 0xb6, 0xf7, 0x22,
	0x21, 0x42, 0x79, 0x64, 0xd2, 0x3a, 0x2f, 0x4e, 0x02, 0x1b, 0x33, 0xbf, 0x80, 0x54, 0x0e, 0xbb,
	0x17, 0xfc, 0x15, 0xb3, 0x9c, 0x95, 0x99, 0x9a, 0x5a, 0xf1, 0xc7, 0x20, 0xdb, 0x98, 0x16, 0x3b,
	0x7f, 0x9c, 0x01, 0xfc, 0x0a, 0x16, 0xd2, 0xd9, 0xef, 0xb6, 0x41, 0x27, 0xe6, 0x39, 0x2b, 0x57,
	0x37, 0xe7, 0x55, 0x10, 0xab, 0xa2, 0x95, 0x8a, 0x4f, 0x8a, 0x3b, 0x38, 0x7d, 0xc2, 0x0e, 0x9d,
	0x36, 0x52, 0xd7, 0x07, 0xa4, 0x59, 0x8f, 0x46, 0xef, 0x69, 0xa3, 0x4c, 0x51, 0x1e, 0xd9, 0x83,
	0xf6, 0x9a, 0x76, 0xca, 0x14, 0xe5, 0xe2, 0x1e, 0x56, 0x72, 0x30, 0x46, 0xe1, 0xd7, 0x80, 0xbd,
	0xe7, 0x97, 0xb0, 0x08, 0x5a, 0x51, 0x26, 0x76, 0xbe, 0x86, 0xf9, 0x9b, 0x3d, 0x60, 0x37, 0xfd,
	0x0f, 0x65, 0x97, 0xd2, 0xd5, 0x6f, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x34, 0x33, 0xcf, 0x11,
	0x8d, 0x01, 0x00, 0x00,
}
