// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sphinx/sphinx_structs.proto

package sphinx

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SphinxPacket struct {
	Hdr                  *Header  `protobuf:"bytes,1,opt,name=Hdr,proto3" json:"Hdr,omitempty"`
	Pld                  []byte   `protobuf:"bytes,2,opt,name=Pld,proto3" json:"Pld,omitempty"`
}

func (m *SphinxPacket) Reset()         { *m = SphinxPacket{} }
func (m *SphinxPacket) String() string { return proto.CompactTextString(m) }
func (*SphinxPacket) ProtoMessage()    {}
func (*SphinxPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_278563119aefb899, []int{0}
}

func (m *SphinxPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SphinxPacket.Unmarshal(m, b)
}
func (m *SphinxPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SphinxPacket.Marshal(b, m, deterministic)
}
func (m *SphinxPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SphinxPacket.Merge(m, src)
}
func (m *SphinxPacket) XXX_Size() int {
	return xxx_messageInfo_SphinxPacket.Size(m)
}
func (m *SphinxPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SphinxPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SphinxPacket proto.InternalMessageInfo

func (m *SphinxPacket) GetHdr() *Header {
	if m != nil {
		return m.Hdr
	}
	return nil
}

func (m *SphinxPacket) GetPld() []byte {
	if m != nil {
		return m.Pld
	}
	return nil
}

type Header struct {
	Alpha                []byte   `protobuf:"bytes,1,opt,name=Alpha,proto3" json:"Alpha,omitempty"`
	Beta                 []byte   `protobuf:"bytes,2,opt,name=Beta,proto3" json:"Beta,omitempty"`
	Mac                  []byte   `protobuf:"bytes,3,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_278563119aefb899, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetAlpha() []byte {
	if m != nil {
		return m.Alpha
	}
	return nil
}

func (m *Header) GetBeta() []byte {
	if m != nil {
		return m.Beta
	}
	return nil
}

func (m *Header) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type Hop struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
}

func (m *Hop) Reset()         { *m = Hop{} }
func (m *Hop) String() string { return proto.CompactTextString(m) }
func (*Hop) ProtoMessage()    {}
func (*Hop) Descriptor() ([]byte, []int) {
	return fileDescriptor_278563119aefb899, []int{2}
}

func (m *Hop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hop.Unmarshal(m, b)
}
func (m *Hop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hop.Marshal(b, m, deterministic)
}
func (m *Hop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hop.Merge(m, src)
}
func (m *Hop) XXX_Size() int {
	return xxx_messageInfo_Hop.Size(m)
}
func (m *Hop) XXX_DiscardUnknown() {
	xxx_messageInfo_Hop.DiscardUnknown(m)
}

var xxx_messageInfo_Hop proto.InternalMessageInfo

func (m *Hop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hop) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Hop) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type RoutingInfo struct {
	NextHop              *Hop      `protobuf:"bytes,1,opt,name=NextHop,proto3" json:"NextHop,omitempty"`
	RoutingCommands      *Commands `protobuf:"bytes,2,opt,name=RoutingCommands,proto3" json:"RoutingCommands,omitempty"`
	NextHopMetaData      []byte    `protobuf:"bytes,3,opt,name=NextHopMetaData,proto3" json:"NextHopMetaData,omitempty"`
	Mac                  []byte    `protobuf:"bytes,4,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (m *RoutingInfo) Reset()         { *m = RoutingInfo{} }
func (m *RoutingInfo) String() string { return proto.CompactTextString(m) }
func (*RoutingInfo) ProtoMessage()    {}
func (*RoutingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_278563119aefb899, []int{3}
}

func (m *RoutingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingInfo.Unmarshal(m, b)
}
func (m *RoutingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingInfo.Marshal(b, m, deterministic)
}
func (m *RoutingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingInfo.Merge(m, src)
}
func (m *RoutingInfo) XXX_Size() int {
	return xxx_messageInfo_RoutingInfo.Size(m)
}
func (m *RoutingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingInfo proto.InternalMessageInfo

func (m *RoutingInfo) GetNextHop() *Hop {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *RoutingInfo) GetRoutingCommands() *Commands {
	if m != nil {
		return m.RoutingCommands
	}
	return nil
}

func (m *RoutingInfo) GetNextHopMetaData() []byte {
	if m != nil {
		return m.NextHopMetaData
	}
	return nil
}

func (m *RoutingInfo) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type Commands struct {
	Delay                float64  `protobuf:"fixed64,1,opt,name=Delay,proto3" json:"Delay,omitempty"`
	Flag                 []byte   `protobuf:"bytes,2,opt,name=Flag,proto3" json:"Flag,omitempty"`
}

func (m *Commands) Reset()         { *m = Commands{} }
func (m *Commands) String() string { return proto.CompactTextString(m) }
func (*Commands) ProtoMessage()    {}
func (*Commands) Descriptor() ([]byte, []int) {
	return fileDescriptor_278563119aefb899, []int{4}
}

func (m *Commands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commands.Unmarshal(m, b)
}
func (m *Commands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commands.Marshal(b, m, deterministic)
}
func (m *Commands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commands.Merge(m, src)
}
func (m *Commands) XXX_Size() int {
	return xxx_messageInfo_Commands.Size(m)
}
func (m *Commands) XXX_DiscardUnknown() {
	xxx_messageInfo_Commands.DiscardUnknown(m)
}

var xxx_messageInfo_Commands proto.InternalMessageInfo

func (m *Commands) GetDelay() float64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *Commands) GetFlag() []byte {
	if m != nil {
		return m.Flag
	}
	return nil
}

type HeaderInitials struct {
	Alpha                []byte   `protobuf:"bytes,1,opt,name=Alpha,proto3" json:"Alpha,omitempty"`
	Secret               []byte   `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"`
	Blinder              []byte   `protobuf:"bytes,3,opt,name=Blinder,proto3" json:"Blinder,omitempty"`
	SecretHash           []byte   `protobuf:"bytes,4,opt,name=SecretHash,proto3" json:"SecretHash,omitempty"`
}

func (m *HeaderInitials) Reset()         { *m = HeaderInitials{} }
func (m *HeaderInitials) String() string { return proto.CompactTextString(m) }
func (*HeaderInitials) ProtoMessage()    {}
func (*HeaderInitials) Descriptor() ([]byte, []int) {
	return fileDescriptor_278563119aefb899, []int{5}
}

func (m *HeaderInitials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderInitials.Unmarshal(m, b)
}
func (m *HeaderInitials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderInitials.Marshal(b, m, deterministic)
}
func (m *HeaderInitials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderInitials.Merge(m, src)
}
func (m *HeaderInitials) XXX_Size() int {
	return xxx_messageInfo_HeaderInitials.Size(m)
}
func (m *HeaderInitials) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderInitials.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderInitials proto.InternalMessageInfo

func (m *HeaderInitials) GetAlpha() []byte {
	if m != nil {
		return m.Alpha
	}
	return nil
}

func (m *HeaderInitials) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *HeaderInitials) GetBlinder() []byte {
	if m != nil {
		return m.Blinder
	}
	return nil
}

func (m *HeaderInitials) GetSecretHash() []byte {
	if m != nil {
		return m.SecretHash
	}
	return nil
}

func init() {
	proto.RegisterType((*SphinxPacket)(nil), "sphinx.SphinxPacket")
	proto.RegisterType((*Header)(nil), "sphinx.Header")
	proto.RegisterType((*Hop)(nil), "sphinx.Hop")
	proto.RegisterType((*RoutingInfo)(nil), "sphinx.RoutingInfo")
	proto.RegisterType((*Commands)(nil), "sphinx.Commands")
	proto.RegisterType((*HeaderInitials)(nil), "sphinx.HeaderInitials")
}

func init() { proto.RegisterFile("sphinx/sphinx_structs.proto", fileDescriptor_278563119aefb899) }

var fileDescriptor_278563119aefb899 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6a, 0xf2, 0x40,
	0x10, 0x25, 0x46, 0xe3, 0xe7, 0x44, 0x54, 0x16, 0x91, 0xc0, 0x07, 0x45, 0x02, 0x05, 0xaf, 0x2c,
	0xd8, 0x5e, 0xf5, 0x4e, 0x2b, 0x6d, 0x42, 0xb1, 0xc8, 0xfa, 0x00, 0x65, 0xcc, 0x6e, 0x35, 0x34,
	0x66, 0x43, 0xb2, 0x82, 0xbe, 0x53, 0x1f, 0xb2, 0x64, 0x7f, 0x6c, 0x11, 0x7a, 0x95, 0x39, 0x33,
	0xe7, 0x9c, 0xcc, 0x1c, 0x16, 0xfe, 0x57, 0xc5, 0x3e, 0xcd, 0x4f, 0x77, 0xfa, 0xf3, 0x5e, 0xc9,
	0xf2, 0x98, 0xc8, 0x6a, 0x5a, 0x94, 0x42, 0x0a, 0xe2, 0xe9, 0x6e, 0xb8, 0x80, 0xee, 0x46, 0x55,
	0x6b, 0x4c, 0x3e, 0xb9, 0x24, 0x63, 0x70, 0x23, 0x56, 0x06, 0xce, 0xd8, 0x99, 0xf8, 0xb3, 0xde,
	0x54, 0xb3, 0xa6, 0x11, 0x47, 0xc6, 0x4b, 0x5a, 0x8f, 0xc8, 0x00, 0xdc, 0x75, 0xc6, 0x82, 0xc6,
	0xd8, 0x99, 0x74, 0x69, 0x5d, 0x86, 0x4b, 0xf0, 0x34, 0x81, 0x0c, 0xa1, 0x35, 0xcf, 0x8a, 0x3d,
	0x2a, 0x7d, 0x97, 0x6a, 0x40, 0x08, 0x34, 0x17, 0x5c, 0xa2, 0x91, 0xa8, 0xba, 0x76, 0x59, 0x61,
	0x12, 0xb8, 0xda, 0x65, 0x85, 0x49, 0xf8, 0x02, 0x6e, 0x24, 0x0a, 0xd2, 0x83, 0x46, 0xcc, 0x94,
	0xbe, 0x43, 0x1b, 0x31, 0x23, 0x01, 0xb4, 0xe7, 0x8c, 0x95, 0xbc, 0xaa, 0x94, 0xbe, 0x43, 0x2d,
	0x24, 0x23, 0xf0, 0xd6, 0xc7, 0xed, 0x2b, 0x3f, 0x1b, 0x17, 0x83, 0xc2, 0x2f, 0x07, 0x7c, 0x2a,
	0x8e, 0x32, 0xcd, 0x77, 0x71, 0xfe, 0x21, 0xc8, 0x2d, 0xb4, 0xdf, 0xf8, 0x49, 0x46, 0xa2, 0x30,
	0x67, 0xf9, 0x97, 0xb3, 0x44, 0x41, 0xed, 0x8c, 0x3c, 0x42, 0xdf, 0xa8, 0x9e, 0xc4, 0xe1, 0x80,
	0x39, 0xd3, 0x3f, 0xf4, 0x67, 0x03, 0x4b, 0xb7, 0x7d, 0x7a, 0x4d, 0x24, 0x13, 0xe8, 0x1b, 0x9b,
	0x15, 0x97, 0xb8, 0x44, 0x89, 0x66, 0xa7, 0xeb, 0xb6, 0xbd, 0xbb, 0xf9, 0x73, 0xf7, 0x03, 0xfc,
	0xbb, 0xf8, 0x0c, 0xa1, 0xb5, 0xe4, 0x19, 0x9e, 0xd5, 0xa2, 0x0e, 0xd5, 0xa0, 0xce, 0xef, 0x39,
	0xc3, 0x9d, 0xcd, 0xaf, 0xae, 0xc3, 0x13, 0xf4, 0x74, 0xe6, 0x71, 0x9e, 0xca, 0x14, 0xb3, 0xea,
	0x8f, 0xec, 0x47, 0xe0, 0x6d, 0x78, 0x52, 0x72, 0x69, 0xd4, 0x06, 0xd5, 0xb1, 0x2e, 0xb2, 0x34,
	0x67, 0xbc, 0x34, 0x9b, 0x5a, 0x48, 0x6e, 0x00, 0x34, 0x27, 0xc2, 0x6a, 0x6f, 0x16, 0xfd, 0xd5,
	0xd9, 0x7a, 0xea, 0x01, 0xdd, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xb4, 0x1a, 0x85, 0x5f,
	0x02, 0x00, 0x00,
}
